from crewai import Agent, Task, Crew
import os
import gradio as gr

# --- Set API Key ---
os.environ["OPENROUTER_API_KEY"] = "your_openrouter_api_key_here"

# --- Define Agents ---
researcher = Agent(
    role="AI Researcher",
    goal="Find accurate and relevant information about any topic.",
    backstory="You are an expert research assistant.",
    verbose=False,
    llm="openrouter/meta-llama/llama-3.1-70b-instruct"
)

writer = Agent(
    role="Content Writer",
    goal="Write engaging content based on research.",
    backstory="You are a professional content writer who explains complex ideas clearly.",
    verbose=False,
    llm="openrouter/openai/gpt-4"
)

# --- Function to run agents ---
def generate_blog(topic):
    # Task 1: Research
    research_task = Task(description=f"Research the topic: '{topic}'", agent=researcher)
    
    # Task 2: Write
    writer_task = Task(description="Write a clear and engaging blog post based on the research.", agent=writer)
    
    # Crew setup
    crew = Crew(agents=[researcher, writer], tasks=[research_task, writer_task])
    
    # Run crew
    result = crew.kickoff()
    return result

# --- Gradio Interface ---
interface = gr.Interface(
    fn=generate_blog,
    inputs=gr.Textbox(lines=2, placeholder="Enter your topic here..."),
    outputs="text",
    title="AI Research & Writing Agent",
    description="Enter a topic and get a research-based blog post generated by AI agents."
)

if __name__ == "__main__":
    interface.launch()
